# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
#rdiscount:
#  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://derek-smith.github.io/
baseurl: /
title: Derek Smith
author: Derek Smith
description: Personal blog and resume
avatar: profile.png
email: codewiththeflow@gmail.com
github: derek-smith # username
twitter: codewiththeflow
linkedin: dereksmith206
stackoverflow: users/1124618/derek-smith   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
# disqus: username
google_analytics: UA-74100433-1


# needed for travis-ci build
exclude: [vendor]
